version: "3.9"

services:
  db:
    image: postgres:16
    container_name: campus-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    image: node:25-alpine
    container_name: campus-api
    working_dir: /app
    volumes:
      - ./apps/api:/app
    command: npm run start:dev
    environment:
      PORT: ${API_PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "${API_PORT}:3000"

  web:
    image: node:25-alpine
    container_name: campus-web
    working_dir: /app
    volumes:
      - ./apps/web:/app
    command: npm run dev -- --host
    depends_on:
      - api
    ports:
      - "${WEB_PORT}:5173"

volumes:
  dbdata:
